import type { Case, UIGraphData, ActionStatus } from '../types';

const API_BASE = (typeof window !== 'undefined' && window.location.hostname === 'localhost' && window.location.port === '5173')
  ? 'http://127.0.0.1:8000/api'
  : '/api';

// 1. Flagship DBT Scholarship Case (Aakash Verma)
const MOCK_FLAGSHIP_CASE: Case = {
  id: "case-flagship-dbt-8821",
  title: "Aakash Verma - Post-Matric Scholarship PFMS Disbursal Blockade",
  citizen_name: "Aakash Verma",
  domain_id: "dbt_failure",
  current_state: "USER_APPROVAL",
  objective: "Post-Matric Scholarship DBT disbursement of ₹48,000 for Aakash Verma was rejected by PFMS central payment gateway with error code BNS-410.",
  blocker_summary: "A police freeze requisition (#CR-4412/Cyber/2026) on Canara Bank account *4401 caused Canara Bank to mark the central NPCI APBS Aadhaar mapper INACTIVE, causing all incoming DBT scholarship payments to fail at PFMS gateway under Rule BNS-410.",
  overall_confidence: 0.94,
  simulated_day: 0,
  facts_summary: [
    "Aakash Verma was awarded ₹48,000 Post-Matric Scholarship for Academic Year 2025-26.",
    "Central PFMS payment batch failed on 2026-02-12 with Error BNS-410 (Account Blocked / Frozen / Inactive).",
    "Ahmedabad Cyber Crime Cell issued Sec 102 CrPC notice on Canara Bank account *4401.",
    "Canara Bank placed a total operational freeze on account *4401 and flagged NPCI mapper as INACTIVE.",
    "Aakash holds an active, unencumbered savings account *8812 with State Bank of India."
  ],
  inferences_summary: [
    "Police freeze was disproportionately applied to entire bank account rather than disputed amount.",
    "Inactivation of NPCI mapper cascaded to central scholarship disbursement failure."
  ],
  contradictions: [],
  candidate_causes: [
    {
      id: "cause-1",
      hypothesis: "Upstream police freeze on Canara Bank triggered NPCI mapper inactivation, blocking central scholarship routing.",
      confidence: 0.94,
      supporting_evidence_ids: ["doc-1", "doc-2", "doc-3"],
      counter_evidence_ids: [],
      unknowns: [],
      causal_chain: ["node-scholarship-approved", "node-payment-attempt", "node-pfms-rejection", "node-npci-mapper", "node-canara-freeze", "node-root-cause", "node-remedial-action"],
      recommended_remedy: "1. Submit formal representation to Canara Bank citing Gujarat HC Sec 102 CrPC precedent.\n2. Execute immediate re-mapping of Aadhaar APBS mandate to active State Bank of India account (*8812)."
    }
  ],
  actions: [
    {
      id: "act-dbt-01",
      action_type: "REPRESENTATION_LETTER",
      target_institution: "Canara Bank (Nodal Branch) & State Bank of India",
      purpose: "Statutory Directive for Aadhaar APBS Remapping to Active SBI Account (*8812)",
      legal_basis: "RBI Master Direction on APBS (DPSS.CO.PD.No.1810/02.14.006/2015-16) & Gujarat HC Sec 102 CrPC",
      status: "PENDING_APPROVAL" as ActionStatus,
      citizen_consent: false,
      created_at: new Date().toISOString(),
      response_deadline: 15,
      generated_content: `MEMORANDUM & STATUTORY REPRESENTATION
To: The Branch Manager, Canara Bank / State Bank of India
Subject: Immediate Remapping of Aadhaar APBS Mandate for Central DBT Entitlements

1. BENEFICIARY DETAILS:
   Citizen Name: Aakash Verma
   Aadhaar Token: ****-****-8821
   Entitlement Scheme: Ministry of Social Justice Post-Matric Scholarship (AY 2025-26)
   Entitlement Value: INR 48,000.00

2. FACTUAL GROUNDING:
   - On 2026-02-12, central PFMS payment batch failed with Error Code BNS-410.
   - Investigation confirms Canara Bank Account *4401 was placed under operational debit freeze.
   - Consequently, the central NPCI APBS mapper was designated INACTIVE.

3. LEGAL PRECEDENT & STATUTORY RELIEF:
   - As per Gujarat High Court (R/SCR.A/1908/2023), omnibus freezes on entire citizen accounts violate proportionality.
   - Under RBI Master Direction DPSS.CO.PD.No.1810, banks must honor customer mandate to remap APBS routing to active accounts.
   
4. RELIEF SOUGHT:
   - Immediate synchronization of NPCI mapper to State Bank of India Account No: *8812.
   - Restoration of ACTIVE APBS routing status for upcoming PFMS payment cycles.

Digitally generated by INDRA Autonomous Administrative Core.`
    }
  ],
  documents: [
    {
      id: "doc-1",
      filename: "Scholarship_Sanction_Order.pdf",
      file_type: "pdf",
      uploaded_at: "2026-01-10T10:00:00Z",
      page_count: 1,
      extractions_count: 3
    },
    {
      id: "doc-2",
      filename: "PFMS_Failure_Report.pdf",
      file_type: "pdf",
      uploaded_at: "2026-02-12T14:30:00Z",
      page_count: 1,
      extractions_count: 2
    },
    {
      id: "doc-3",
      filename: "Canara_Bank_Freeze_Notice.pdf",
      file_type: "pdf",
      uploaded_at: "2026-02-04T09:15:00Z",
      page_count: 1,
      extractions_count: 3
    },
    {
      id: "doc-4",
      filename: "SBI_Active_Account_Statement.pdf",
      file_type: "pdf",
      uploaded_at: "2026-02-15T11:00:00Z",
      page_count: 1,
      extractions_count: 2
    },
    {
      id: "doc-5",
      filename: "NPCI_Mapper_Status.pdf",
      file_type: "pdf",
      uploaded_at: "2026-02-14T16:45:00Z",
      page_count: 1,
      extractions_count: 2
    }
  ],
  nodes: [],
  edges: [],
  timeline: [],
  unknowns: [],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString()
};

// 2. EPFO Pension & PF Case (Pooja Sharma)
const MOCK_EPFO_CASE: Case = {
  id: "case-epfo-claim-9912",
  title: "Pooja Sharma - EPFO Form 19 Claim Settlement Rejection",
  citizen_name: "Pooja Sharma",
  domain_id: "epfo_claim",
  current_state: "USER_APPROVAL",
  objective: "EPFO Form 19 Final PF Settlement claim was rejected citing date of exit mismatch between employer return and member portal.",
  blocker_summary: "Conflicting Date of Exit records between Relieving Letter (2025-10-31) and Electronic Challan Return (2025-11-15) triggered automated claim rejection Rule EPF-R09.",
  overall_confidence: 0.96,
  simulated_day: 0,
  facts_summary: [
    "Pooja Sharma submitted Form 19 Final PF Settlement for UAN 100984210988.",
    "Field Office rejected claim on 2026-01-20 citing Rule EPF-R09.",
    "Relieving Letter from TechSys Pvt Ltd states Date of Relieving: 2025-10-31.",
    "Employer ECR filing submitted Date of Exit: 2025-11-15."
  ],
  inferences_summary: [
    "Clerical error in employer ECR submission caused automated system discrepancy rejection."
  ],
  contradictions: [
    {
      id: "contra-1",
      field: "date_of_exit",
      node_a_id: "node-relieving",
      node_b_id: "node-ecr-conflict",
      description: "Contradiction in official Exit Date between Relieving Letter and Employer ECR Filing.",
      value_a: "2025-10-31 (Relieving Certificate)",
      value_b: "2025-11-15 (ECR Return)",
      severity: "HIGH",
      resolved: false
    }
  ],
  candidate_causes: [
    {
      id: "cause-epfo-1",
      hypothesis: "Clerical error in employer ECR submission caused automated system discrepancy rejection.",
      confidence: 0.96,
      supporting_evidence_ids: ["doc-epfo-1", "doc-epfo-2"],
      counter_evidence_ids: [],
      unknowns: [],
      causal_chain: ["node-relieving", "node-ecr-conflict", "node-epfo-rejection", "node-joint-declaration"],
      recommended_remedy: "Submit Joint Declaration Form with certified Relieving Letter under EPFO SOP v3.0 (2024)."
    }
  ],
  actions: [
    {
      id: "act-epfo-01",
      action_type: "REPRESENTATION_LETTER",
      target_institution: "EPFO Regional Office (Bandra)",
      purpose: "Digital Joint Declaration Correction under EPFO SOP Version 3.0 (2024)",
      legal_basis: "EPFO Joint Declaration Circular WS/2024/7741",
      status: "PENDING_APPROVAL" as ActionStatus,
      citizen_consent: false,
      created_at: new Date().toISOString(),
      response_deadline: 15,
      generated_content: `JOINT DECLARATION APPLICATION (EPFO SOP v3.0)
To: Regional P.F. Commissioner, EPFO Regional Office
Subject: Correction of Date of Exit for UAN: 100984210988

Beneficiary: Pooja Sharma
Member ID: MH/BAN/0049182/000/0019281

1. DISCREPANCY:
   Employer ECR incorrectly logged Date of Exit as 2025-11-15 instead of 2025-10-31.

2. SUBSTANTIATING EVIDENCE:
   Attached Relieving Letter & Service Certificate dated 2025-10-31.

Digitally verified via INDRA Case Intelligence.`
    }
  ],
  documents: [
    {
      id: "doc-epfo-1",
      filename: "Relieving_and_Experience_Letter.pdf",
      file_type: "pdf",
      uploaded_at: "2025-11-01T10:00:00Z",
      page_count: 1,
      extractions_count: 2
    },
    {
      id: "doc-epfo-2",
      filename: "Employer_ECR_Filing_Extract.pdf",
      file_type: "pdf",
      uploaded_at: "2025-11-20T12:30:00Z",
      page_count: 1,
      extractions_count: 2
    }
  ],
  nodes: [],
  edges: [],
  timeline: [],
  unknowns: [],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString()
};

let localCaseStore: Record<string, Case> = {
  "case-flagship-dbt-8821": { ...MOCK_FLAGSHIP_CASE },
  "case-epfo-claim-9912": { ...MOCK_EPFO_CASE }
};

export const api = {
  async getDomains() {
    try {
      const res = await fetch(`${API_BASE}/domains`);
      if (res.ok) return await res.json();
    } catch (e) {}
    return [
      { id: "dbt_failure", name: "DBT Direct Benefit Transfer", description: "Welfare & scholarship payment blockades (Flagship)" },
      { id: "epfo_claim", name: "EPFO Pension & PF Claims", description: "Provident fund withdrawal and exit date disputes" }
    ];
  },

  async getCases(): Promise<Case[]> {
    try {
      const res = await fetch(`${API_BASE}/cases`);
      if (res.ok) return await res.json();
    } catch (e) {}
    return Object.values(localCaseStore);
  },

  async getCase(caseId: string): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}`);
      if (res.ok) return await res.json();
    } catch (e) {}
    return localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
  },

  async createCase(data: { title: string; citizen_name: string; domain_id: string; objective?: string }): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const template = data.domain_id === 'epfo_claim' ? MOCK_EPFO_CASE : MOCK_FLAGSHIP_CASE;
    const newCase = { ...template };
    newCase.id = `case-${Date.now()}`;
    newCase.title = data.title;
    newCase.citizen_name = data.citizen_name;
    localCaseStore[newCase.id] = newCase;
    return newCase;
  },

  async ingestFlagship(caseId: string): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/ingest-flagship`, { method: 'POST' });
      if (res.ok) return await res.json();
    } catch (e) {}
    return localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
  },

  async triggerReasoning(caseId: string): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/reason`, { method: 'POST' });
      if (res.ok) return await res.json();
    } catch (e) {}
    return localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
  },

  async grantConsent(caseId: string, actionId: string, consent: boolean = true) {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/actions/${actionId}/consent`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ consent }),
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.actions = c.actions.map(a => a.id === actionId ? { ...a, citizen_consent: consent, status: (consent ? 'APPROVED' : 'PENDING_APPROVAL') as ActionStatus } : a);
    c.current_state = consent ? 'ACTION_REQUIRED' : 'USER_APPROVAL';
    return { status: "SUCCESS", case: c };
  },

  async submitAction(caseId: string, actionId: string) {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/actions/${actionId}/submit`, {
        method: 'POST',
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.actions = c.actions.map(a => a.id === actionId ? { ...a, status: 'SUBMITTED' as ActionStatus } : a);
    c.current_state = 'WAITING';
    return { status: "SUCCESS", case: c };
  },

  async advanceTime(caseId: string, days: number = 15): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/advance-time`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ days }),
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.current_state = 'ESCALATION_REQUIRED';
    return c;
  },

  async simulateEvent(caseId: string, eventType: string): Promise<any> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/simulate-event`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ event_type: eventType }),
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    return { status: "SIMULATED", event: eventType };
  },

  async resolveDbtChain(caseId: string) {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/resolve-dbt-chain`, {
        method: 'POST',
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.current_state = 'RESOLUTION';
    return { status: "RESOLVED", utr: "PFMS-UTR-34F5BBFFF2", case: c };
  },

  async executeAutopilot(caseId: string) {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/autopilot`, {
        method: 'POST',
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.actions = c.actions.map(a => ({ ...a, citizen_consent: true, status: 'SUBMITTED' as ActionStatus }));
    c.current_state = 'RESOLUTION';
    return { status: "AUTONOMOUS_SUCCESS", utr: "PFMS-UTR-34F5BBFFF2", case: c };
  },

  async getGraph(caseId: string): Promise<UIGraphData> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/graph`);
      if (res.ok) return await res.json();
    } catch (e) {}

    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    if (c.domain_id === 'epfo_claim') {
      return {
        nodes: [
          { id: "node-relieving", label: "Relieving Certificate (2025-10-31)", type: "EVIDENCE", attributes: { document: "Relieving Letter", exit_date: "2025-10-31" }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 },
          { id: "node-ecr-conflict", label: "Employer ECR Return (2025-11-15)", type: "EVIDENCE", attributes: { document: "ECR Return", exit_date: "2025-11-15" }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 },
          { id: "node-epfo-rejection", label: "EPFO Rejection Rule EPF-R09", type: "RULE", attributes: { rule: "EPF-R09", reason: "Exit Date Mismatch" }, epistemic_category: "RULE", status: "APPLIED", confidence: 1.0 },
          { id: "node-joint-declaration", label: "Joint Declaration Action", type: "ACTION", attributes: { sop: "v3.0", sla: "15d" }, epistemic_category: "FACT", status: "DRAFTED", confidence: 0.96 }
        ],
        edges: [
          { id: "e-ep1", source_id: "node-relieving", target_id: "node-ecr-conflict", label: "CONTRADICTS_EXIT_DATE", type: "CONTRADICTS", attributes: {}, confidence: 1.0 },
          { id: "e-ep2", source_id: "node-ecr-conflict", target_id: "node-epfo-rejection", label: "TRIGGERS_REJECTION", type: "CAUSED_BY", attributes: {}, confidence: 1.0 },
          { id: "e-ep3", source_id: "node-epfo-rejection", target_id: "node-joint-declaration", label: "REQUIRES_RECTIFICATION", type: "CAUSED_BY", attributes: {}, confidence: 1.0 }
        ],
        stats: { total_nodes: 4, total_edges: 3, facts_count: 2, inferences_count: 0, rules_count: 1, contradictions_count: 1 }
      };
    }

    // Flagship DBT Complete Causal Graph
    return {
      nodes: [
        { id: "node-scholarship-approved", label: "Scholarship Approved (₹48,000)", type: "EVENT", attributes: { scheme: "Post-Matric", amount: 48000 }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 },
        { id: "node-payment-attempt", label: "Central PFMS Payment Attempt", type: "TRANSACTION", attributes: { gateway: "PFMS Central", batch: "BT-99120" }, epistemic_category: "EVENT", status: "VERIFIED", confidence: 1.0 },
        { id: "node-pfms-rejection", label: "PFMS Rejection (Error BNS-410)", type: "RULE", attributes: { error_code: "BNS-410", meaning: "Account Inactive/Restricted" }, epistemic_category: "RULE", status: "APPLIED", confidence: 1.0 },
        { id: "node-npci-mapper", label: "NPCI APBS Mapper Status = INACTIVE", type: "TRANSACTION", attributes: { mapper_status: "INACTIVE", routing: "Canara *4401" }, epistemic_category: "SYSTEM_OBSERVATION", status: "VERIFIED", confidence: 0.98 },
        { id: "node-canara-freeze", label: "Canara Bank Account Restricting Freeze", type: "ACTION", attributes: { bank: "Canara Bank", account: "*4401", notice: "Sec 102 CrPC" }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 },
        { id: "node-root-cause", label: "Root Cause: Upstream Police Freeze Inactivated APBS", type: "DEPENDENCY", attributes: { confidence: 0.94, hypothesis: "Police requisition triggered cascade" }, epistemic_category: "INFERENCE", status: "VERIFIED", confidence: 0.94 },
        { id: "node-remedial-action", label: "Remedial Action: APBS Remap to Active SBI Account", type: "ACTION", attributes: { target: "State Bank of India", account: "*8812" }, epistemic_category: "ACTION", status: "PENDING_APPROVAL", confidence: 0.96 }
      ],
      edges: [
        { id: "e1", source_id: "node-scholarship-approved", target_id: "node-payment-attempt", label: "INITIATES_DISBURSAL", type: "CAUSED_BY", attributes: {}, confidence: 1.0 },
        { id: "e2", source_id: "node-payment-attempt", target_id: "node-pfms-rejection", label: "FAILS_WITH_ERROR", type: "CAUSED_BY", attributes: {}, confidence: 1.0 },
        { id: "e3", source_id: "node-pfms-rejection", target_id: "node-npci-mapper", label: "CAUSED_BY_INACTIVE_MAPPER", type: "DEPENDS_ON", attributes: {}, confidence: 1.0 },
        { id: "e4", source_id: "node-npci-mapper", target_id: "node-canara-freeze", label: "RESULT_OF_BANK_FREEZE", type: "CAUSED_BY", attributes: {}, confidence: 1.0 },
        { id: "e5", source_id: "node-canara-freeze", target_id: "node-root-cause", label: "IDENTIFIED_AS_ROOT_CAUSE", type: "PROVES", attributes: {}, confidence: 0.94 },
        { id: "e6", source_id: "node-root-cause", target_id: "node-remedial-action", label: "GENERATES_ACTION", type: "REQUIRES", attributes: {}, confidence: 0.96 }
      ],
      stats: { total_nodes: 7, total_edges: 6, facts_count: 3, inferences_count: 1, rules_count: 1, contradictions_count: 0 }
    };
  },

  async resetMockState() {
    try {
      const res = await fetch(`${API_BASE}/reset`, { method: 'POST' });
      if (res.ok) return await res.json();
    } catch (e) {}
    localCaseStore = {
      "case-flagship-dbt-8821": { ...MOCK_FLAGSHIP_CASE },
      "case-epfo-claim-9912": { ...MOCK_EPFO_CASE }
    };
    return { status: "RESET" };
  }
};
