import type { Case, UIGraphData, ActionStatus } from '../types';

const API_BASE = (typeof window !== 'undefined' && window.location.hostname === 'localhost' && window.location.port === '5173')
  ? 'http://127.0.0.1:8000/api'
  : '/api';

// 1. Flagship DBT Scholarship Case (Aakash Verma)
const MOCK_FLAGSHIP_CASE: Case = {
  id: "case-flagship-dbt-8821",
  title: "Aakash Verma - Post-Matric Scholarship PFMS Disbursal Blockade",
  citizen_name: "Aakash Verma",
  domain_id: "dbt_failure",
  current_state: "USER_APPROVAL",
  objective: "Post-Matric Scholarship DBT disbursement of ₹48,000 for Aakash Verma was rejected by PFMS central payment gateway with error code BNS-410.",
  blocker_summary: "A police freeze requisition (#CR-4412/Cyber/2026) on Canara Bank account *4401 caused Canara Bank to mark the central NPCI APBS Aadhaar mapper INACTIVE, causing all incoming DBT scholarship payments to fail at PFMS gateway under Rule BNS-410.",
  overall_confidence: 0.94,
  simulated_day: 0,
  facts_summary: [
    "Aakash Verma was awarded ₹48,000 Post-Matric Scholarship for Academic Year 2025-26.",
    "Central PFMS payment batch failed on 2026-02-12 with Error BNS-410 (Account Blocked / Frozen / Inactive).",
    "Ahmedabad Cyber Crime Cell issued Sec 102 CrPC notice on Canara Bank account *4401.",
    "Canara Bank placed a total operational freeze on account *4401 and flagged NPCI mapper as INACTIVE.",
    "Aakash holds an active, unencumbered savings account *8812 with State Bank of India."
  ],
  inferences_summary: [
    "Police freeze was disproportionately applied to entire bank account rather than disputed amount.",
    "Inactivation of NPCI mapper cascaded to central scholarship disbursement failure."
  ],
  contradictions: [],
  candidate_causes: [
    {
      id: "cause-1",
      hypothesis: "Upstream police freeze on Canara Bank triggered NPCI mapper inactivation, blocking central scholarship routing.",
      confidence: 0.94,
      supporting_evidence_ids: ["doc-1", "doc-2", "doc-3"],
      counter_evidence_ids: [],
      unknowns: [],
      causal_chain: ["node-cyber-notice", "node-canara-freeze", "node-npci-mapper", "node-pfms-rejection", "node-scholarship-loss"],
      recommended_remedy: "1. Submit formal representation to Canara Bank citing Gujarat HC Sec 102 CrPC precedent.\n2. Execute immediate re-mapping of Aadhaar APBS mandate to active State Bank of India account (*8812)."
    }
  ],
  actions: [
    {
      id: "act-dbt-01",
      action_type: "REPRESENTATION_LETTER",
      target_institution: "Canara Bank (Nodal Branch) & State Bank of India",
      purpose: "Statutory Directive for Aadhaar APBS Remapping to Active SBI Account (*8812)",
      legal_basis: "RBI Master Direction on APBS (DPSS.CO.PD.No.1810/02.14.006/2015-16) & Gujarat HC Sec 102 CrPC",
      status: "PENDING_APPROVAL" as ActionStatus,
      citizen_consent: false,
      created_at: new Date().toISOString(),
      response_deadline: 15,
      generated_content: `MEMORANDUM & STATUTORY REPRESENTATION
To: The Branch Manager, Canara Bank / State Bank of India
Subject: Immediate Remapping of Aadhaar APBS Mandate for Central DBT Entitlements

1. BENEFICIARY DETAILS:
   Citizen Name: Aakash Verma
   Aadhaar Token: ****-****-8821
   Entitlement Scheme: Ministry of Social Justice Post-Matric Scholarship (AY 2025-26)
   Entitlement Value: INR 48,000.00

2. FACTUAL GROUNDING:
   - On 2026-02-12, central PFMS payment batch failed with Error Code BNS-410.
   - Investigation confirms Canara Bank Account *4401 was placed under operational debit freeze.
   - Consequently, the central NPCI APBS mapper was designated INACTIVE.

3. LEGAL PRECEDENT & STATUTORY RELIEF:
   - As per Gujarat High Court (R/SCR.A/1908/2023), omnibus freezes on entire citizen accounts violate proportionality.
   - Under RBI Master Direction DPSS.CO.PD.No.1810, banks must honor customer mandate to remap APBS routing to active accounts.
   
4. RELIEF SOUGHT:
   - Immediate synchronization of NPCI mapper to State Bank of India Account No: *8812.
   - Restoration of ACTIVE APBS routing status for upcoming PFMS payment cycles.

Digitally generated by INDRA Autonomous Administrative Core.`
    }
  ],
  documents: [
    {
      id: "doc-1",
      filename: "Scholarship_Sanction_Order.pdf",
      file_type: "pdf",
      uploaded_at: "2026-01-10T10:00:00Z",
      page_count: 1,
      extractions_count: 3
    },
    {
      id: "doc-2",
      filename: "PFMS_Failure_Report.pdf",
      file_type: "pdf",
      uploaded_at: "2026-02-12T14:30:00Z",
      page_count: 1,
      extractions_count: 2
    },
    {
      id: "doc-3",
      filename: "Canara_Bank_Freeze_Notice.pdf",
      file_type: "pdf",
      uploaded_at: "2026-02-04T09:15:00Z",
      page_count: 1,
      extractions_count: 3
    },
    {
      id: "doc-4",
      filename: "SBI_Active_Account_Statement.pdf",
      file_type: "pdf",
      uploaded_at: "2026-02-15T11:00:00Z",
      page_count: 1,
      extractions_count: 2
    },
    {
      id: "doc-5",
      filename: "NPCI_Mapper_Status.pdf",
      file_type: "pdf",
      uploaded_at: "2026-02-14T16:45:00Z",
      page_count: 1,
      extractions_count: 2
    }
  ],
  nodes: [],
  edges: [],
  timeline: [],
  unknowns: [],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString()
};

// 2. EPFO Pension & PF Case (Pooja Sharma)
const MOCK_EPFO_CASE: Case = {
  id: "case-epfo-claim-9912",
  title: "Pooja Sharma - EPFO Form 19 Claim Settlement Rejection",
  citizen_name: "Pooja Sharma",
  domain_id: "epfo_claim",
  current_state: "USER_APPROVAL",
  objective: "EPFO Form 19 Final PF Settlement claim was rejected citing date of exit mismatch between employer return and member portal.",
  blocker_summary: "Conflicting Date of Exit records between Relieving Letter (2025-10-31) and Electronic Challan Return (2025-11-15) triggered automated claim rejection Rule EPF-R09.",
  overall_confidence: 0.96,
  simulated_day: 0,
  facts_summary: [
    "Pooja Sharma submitted Form 19 Final PF Settlement for UAN 100984210988.",
    "Field Office rejected claim on 2026-01-20 citing Rule EPF-R09.",
    "Relieving Letter from TechSys Pvt Ltd states Date of Relieving: 2025-10-31.",
    "Employer ECR filing submitted Date of Exit: 2025-11-15."
  ],
  inferences_summary: [
    "Clerical error in employer ECR submission caused automated system discrepancy rejection."
  ],
  contradictions: [
    {
      id: "contra-1",
      field: "date_of_exit",
      node_a_id: "node-relieving",
      node_b_id: "node-ecr-conflict",
      description: "Contradiction in official Exit Date between Relieving Letter and Employer ECR Filing.",
      value_a: "2025-10-31 (Relieving Certificate)",
      value_b: "2025-11-15 (ECR Return)",
      severity: "HIGH",
      resolved: false
    }
  ],
  candidate_causes: [
    {
      id: "cause-epfo-1",
      hypothesis: "Clerical error in employer ECR submission caused automated system discrepancy rejection.",
      confidence: 0.96,
      supporting_evidence_ids: ["doc-epfo-1", "doc-epfo-2"],
      counter_evidence_ids: [],
      unknowns: [],
      causal_chain: ["node-relieving", "node-ecr-conflict", "node-epfo-rejection"],
      recommended_remedy: "Submit Joint Declaration Form with certified Relieving Letter under EPFO SOP v3.0 (2024)."
    }
  ],
  actions: [
    {
      id: "act-epfo-01",
      action_type: "REPRESENTATION_LETTER",
      target_institution: "EPFO Regional Office (Bandra)",
      purpose: "Digital Joint Declaration Correction under EPFO SOP Version 3.0 (2024)",
      legal_basis: "EPFO Joint Declaration Circular WS/2024/7741",
      status: "PENDING_APPROVAL" as ActionStatus,
      citizen_consent: false,
      created_at: new Date().toISOString(),
      response_deadline: 15,
      generated_content: `JOINT DECLARATION APPLICATION (EPFO SOP v3.0)
To: Regional P.F. Commissioner, EPFO Regional Office
Subject: Correction of Date of Exit for UAN: 100984210988

Beneficiary: Pooja Sharma
Member ID: MH/BAN/0049182/000/0019281

1. DISCREPANCY:
   Employer ECR incorrectly logged Date of Exit as 2025-11-15 instead of 2025-10-31.

2. SUBSTANTIATING EVIDENCE:
   Attached Relieving Letter & Service Certificate dated 2025-10-31.

Digitally verified via INDRA Case Intelligence.`
    }
  ],
  documents: [
    {
      id: "doc-epfo-1",
      filename: "Relieving_and_Experience_Letter.pdf",
      file_type: "pdf",
      uploaded_at: "2025-11-01T10:00:00Z",
      page_count: 1,
      extractions_count: 2
    },
    {
      id: "doc-epfo-2",
      filename: "Employer_ECR_Filing_Extract.pdf",
      file_type: "pdf",
      uploaded_at: "2025-11-20T12:30:00Z",
      page_count: 1,
      extractions_count: 2
    }
  ],
  nodes: [],
  edges: [],
  timeline: [],
  unknowns: [],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString()
};

// 3. New Domain: PMAY Gramin Housing Subsidy (Ramesh Kumar)
const MOCK_PMAY_CASE: Case = {
  id: "case-pmay-housing-7734",
  title: "Ramesh Kumar - PMAY-G Housing Subsidy 2nd Tranche Blockade",
  citizen_name: "Ramesh Kumar",
  domain_id: "pmay_housing",
  current_state: "USER_APPROVAL",
  objective: "PMAY-G 2nd installment of ₹70,000 (Total ₹1,20,000) withheld due to geo-tagging coordinate discrepancy at lintel level inspection.",
  blocker_summary: "Gram Panchayat field inspector logged geo-tag coordinates with a 140-meter GPS drift, causing automated satellite cross-verification to flag the construction as 'UNVERIFIED / OUT OF PLOT' under Rule PMAY-GEO-04.",
  overall_confidence: 0.97,
  simulated_day: 0,
  facts_summary: [
    "Ramesh Kumar was sanctioned ₹1,20,000 for rural pucca house construction under PMAY-G.",
    "1st installment (₹40,000) successfully disbursed upon plinth completion.",
    "Lintel inspection geo-tag was recorded at 23.0225° N, 72.5714° E (Gram Panchayat phone drift).",
    "Registered beneficiary land parcel is at 23.0238° N, 72.5719° E (Survey No: 402/1).",
    "Physical construction is 100% verified on citizen's actual land parcel."
  ],
  inferences_summary: [
    "GPS signal degradation in rural field phone caused coordinate offset during lintel inspection.",
    "Automated GIS validation halted 2nd tranche release without notifying the beneficiary."
  ],
  contradictions: [
    {
      id: "contra-pmay-1",
      field: "gps_coordinates",
      node_a_id: "node-land-record",
      node_b_id: "node-inspector-tag",
      description: "Discrepancy between Registered Land Title GPS (23.0238° N) and Field Officer Geo-tag (23.0225° N).",
      value_a: "23.0238° N, 72.5719° E (Land Registry)",
      value_b: "23.0225° N, 72.5714° E (Inspector App)",
      severity: "HIGH",
      resolved: false
    }
  ],
  candidate_causes: [
    {
      id: "cause-pmay-1",
      hypothesis: "Hardware GPS drift during field inspector photo capture triggered automated GIS plot boundary mismatch.",
      confidence: 0.97,
      supporting_evidence_ids: ["doc-pmay-1", "doc-pmay-2"],
      counter_evidence_ids: [],
      unknowns: [],
      causal_chain: ["node-land-title", "node-gps-drift", "node-gis-block", "node-pmay-withheld"],
      recommended_remedy: "Request Block Development Officer (BDO) geo-tag override with certified Patwari boundary report under PMAY-G Grievance Framework 2024."
    }
  ],
  actions: [
    {
      id: "act-pmay-01",
      action_type: "REPRESENTATION_LETTER",
      target_institution: "District Rural Development Agency (DRDA) & BDO Office",
      purpose: "Administrative Re-Verification & Geo-Tag Coordinate Override for PMAY-G Tranche 2",
      legal_basis: "Ministry of Rural Development PMAY-G Guidelines (Sec 6.4 - Geo-Tag Dispute Resolution)",
      status: "PENDING_APPROVAL" as ActionStatus,
      citizen_consent: false,
      created_at: new Date().toISOString(),
      response_deadline: 15,
      generated_content: `REPRESENTATION FOR PMAY-G GEO-TAG CORRECTION
To: The Project Director, DRDA / Block Development Officer
Subject: Rectification of Lintel Stage Geo-Tag Coordinates for PMAY-G ID: GJ-2025-PMAY-88192

Beneficiary: Ramesh Kumar
Scheme: Pradhan Mantri Awaas Yojana - Gramin

1. FACTUAL DISCREPANCY:
   Lintel inspection photo recorded erroneous coordinates due to mobile device GPS calibration error (140m offset).

2. VERIFIED EVIDENCE:
   Attached Revenue Land Record (Survey 402/1) and Patwari physical inspection certificate confirming genuine on-site construction.

3. PRAYER:
   Execute administrative coordinate override on AwaasSoft portal and release 2nd tranche of INR 70,000.00.

Generated by INDRA Administrative Intelligence.`
    }
  ],
  documents: [
    {
      id: "doc-pmay-1",
      filename: "PMAYG_Sanction_and_Inspection_Card.pdf",
      file_type: "pdf",
      uploaded_at: "2025-12-05T09:00:00Z",
      page_count: 1,
      extractions_count: 3
    },
    {
      id: "doc-pmay-2",
      filename: "Revenue_Land_Title_Survey_402.pdf",
      file_type: "pdf",
      uploaded_at: "2026-01-14T11:20:00Z",
      page_count: 1,
      extractions_count: 2
    }
  ],
  nodes: [],
  edges: [],
  timeline: [],
  unknowns: [],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString()
};

let localCaseStore: Record<string, Case> = {
  "case-flagship-dbt-8821": { ...MOCK_FLAGSHIP_CASE },
  "case-epfo-claim-9912": { ...MOCK_EPFO_CASE },
  "case-pmay-housing-7734": { ...MOCK_PMAY_CASE }
};

export const api = {
  async getDomains() {
    try {
      const res = await fetch(`${API_BASE}/domains`);
      if (res.ok) return await res.json();
    } catch (e) {}
    return [
      { id: "dbt_failure", name: "DBT Direct Benefit Transfer", description: "Welfare & scholarship payment blockades (Flagship)" },
      { id: "epfo_claim", name: "EPFO Pension & PF Claims", description: "Provident fund withdrawal and exit date disputes" },
      { id: "pmay_housing", name: "PMAY-G Rural Housing Subsidies", description: "Construction tranche release & geo-tag resolution" }
    ];
  },

  async getCases(): Promise<Case[]> {
    try {
      const res = await fetch(`${API_BASE}/cases`);
      if (res.ok) return await res.json();
    } catch (e) {}
    return Object.values(localCaseStore);
  },

  async getCase(caseId: string): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}`);
      if (res.ok) return await res.json();
    } catch (e) {}
    return localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
  },

  async createCase(data: { title: string; citizen_name: string; domain_id: string; objective?: string }): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const template = data.domain_id === 'epfo_claim'
      ? MOCK_EPFO_CASE
      : data.domain_id === 'pmay_housing'
      ? MOCK_PMAY_CASE
      : MOCK_FLAGSHIP_CASE;
    const newCase = { ...template };
    newCase.id = `case-${Date.now()}`;
    newCase.title = data.title;
    newCase.citizen_name = data.citizen_name;
    localCaseStore[newCase.id] = newCase;
    return newCase;
  },

  async ingestFlagship(caseId: string): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/ingest-flagship`, { method: 'POST' });
      if (res.ok) return await res.json();
    } catch (e) {}
    return localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
  },

  async triggerReasoning(caseId: string): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/reason`, { method: 'POST' });
      if (res.ok) return await res.json();
    } catch (e) {}
    return localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
  },

  async grantConsent(caseId: string, actionId: string, consent: boolean = true) {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/actions/${actionId}/consent`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ consent }),
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.actions = c.actions.map(a => a.id === actionId ? { ...a, citizen_consent: consent, status: (consent ? 'APPROVED' : 'PENDING_APPROVAL') as ActionStatus } : a);
    c.current_state = consent ? 'ACTION_REQUIRED' : 'USER_APPROVAL';
    return { status: "SUCCESS", case: c };
  },

  async submitAction(caseId: string, actionId: string) {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/actions/${actionId}/submit`, {
        method: 'POST',
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.actions = c.actions.map(a => a.id === actionId ? { ...a, status: 'SUBMITTED' as ActionStatus } : a);
    c.current_state = 'WAITING';
    return { status: "SUCCESS", case: c };
  },

  async advanceTime(caseId: string, days: number = 15): Promise<Case> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/advance-time`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ days }),
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.current_state = 'ESCALATION_REQUIRED';
    return c;
  },

  async simulateEvent(caseId: string, eventType: string): Promise<any> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/simulate-event`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ event_type: eventType }),
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    return { status: "SIMULATED", event: eventType };
  },

  async resolveDbtChain(caseId: string) {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/resolve-dbt-chain`, {
        method: 'POST',
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.current_state = 'RESOLUTION';
    return { status: "RESOLVED", utr: "PFMS-UTR-34F5BBFFF2", case: c };
  },

  async executeAutopilot(caseId: string) {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/autopilot`, {
        method: 'POST',
      });
      if (res.ok) return await res.json();
    } catch (e) {}
    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    c.actions = c.actions.map(a => ({ ...a, citizen_consent: true, status: 'SUBMITTED' as ActionStatus }));
    c.current_state = 'RESOLUTION';
    return { status: "AUTONOMOUS_SUCCESS", utr: "PFMS-UTR-34F5BBFFF2", case: c };
  },

  async getGraph(caseId: string): Promise<UIGraphData> {
    try {
      const res = await fetch(`${API_BASE}/cases/${caseId}/graph`);
      if (res.ok) return await res.json();
    } catch (e) {}

    const c = localCaseStore[caseId] || localCaseStore["case-flagship-dbt-8821"];
    if (c.domain_id === 'pmay_housing') {
      return {
        nodes: [
          { id: "node-land-title", label: "Land Title Survey 402/1", type: "EVIDENCE", attributes: { parcel: "Survey 402/1", village: "Sanand" }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 },
          { id: "node-gps-drift", label: "Field Phone 140m GPS Drift", type: "ACTION", attributes: { drift_meters: 140, device: "DRDA App" }, epistemic_category: "FACT", status: "VERIFIED", confidence: 0.96 },
          { id: "node-gis-block", label: "AwaasSoft Rule PMAY-GEO-04", type: "RULE", attributes: { code: "PMAY-GEO-04", threshold: "50m" }, epistemic_category: "RULE", status: "APPLIED", confidence: 1.0 },
          { id: "node-pmay-withheld", label: "₹70,000 Tranche 2 Withheld", type: "EVENT", attributes: { tranche: 2, amount: 70000 }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 }
        ],
        edges: [
          { id: "e-p1", source_id: "node-land-title", target_id: "node-gps-drift", label: "CONTRADICTS_COORDINATES", type: "CONTRADICTS", attributes: {}, confidence: 1.0 },
          { id: "e-p2", source_id: "node-gps-drift", target_id: "node-gis-block", label: "TRIGGERS_REJECTION_RULE", type: "CAUSED_BY", attributes: {}, confidence: 1.0 },
          { id: "e-p3", source_id: "node-gis-block", target_id: "node-pmay-withheld", label: "HALTS_DISBURSAL", type: "CAUSED_BY", attributes: {}, confidence: 1.0 }
        ],
        stats: { total_nodes: 4, total_edges: 3, facts_count: 3, inferences_count: 0, rules_count: 1, contradictions_count: 1 }
      };
    }

    return {
      nodes: [
        { id: "node-cyber-notice", label: "Police Notice #CR-4412", type: "EVIDENCE", attributes: { authority: "Cyber Crime Cell", section: "102 CrPC" }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 },
        { id: "node-canara-freeze", label: "Canara Account Debit Freeze", type: "ACTION", attributes: { bank: "Canara Bank", account: "*4401" }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 },
        { id: "node-npci-mapper", label: "NPCI APBS Mapper Inactive", type: "TRANSACTION", attributes: { mapper_status: "INACTIVE" }, epistemic_category: "SYSTEM_OBSERVATION", status: "VERIFIED", confidence: 0.98 },
        { id: "node-pfms-rejection", label: "PFMS Rejection Error BNS-410", type: "RULE", attributes: { code: "BNS-410", treasury: "Central PFMS" }, epistemic_category: "RULE", status: "APPLIED", confidence: 1.0 },
        { id: "node-scholarship-loss", label: "₹48,000 Scholarship Withheld", type: "EVENT", attributes: { amount: 48000, student: "Aakash Verma" }, epistemic_category: "FACT", status: "VERIFIED", confidence: 1.0 }
      ],
      edges: [
        { id: "e1", source_id: "node-cyber-notice", target_id: "node-canara-freeze", label: "TRIGGERS_FREEZE", type: "CAUSED_BY", attributes: {}, confidence: 1.0 },
        { id: "e2", source_id: "node-canara-freeze", target_id: "node-npci-mapper", label: "INVALIDATES_MAPPER", type: "CAUSED_BY", attributes: {}, confidence: 1.0 },
        { id: "e3", source_id: "node-npci-mapper", target_id: "node-pfms-rejection", label: "CAUSES_REJECTION", type: "CAUSED_BY", attributes: {}, confidence: 1.0 },
        { id: "e4", source_id: "node-pfms-rejection", target_id: "node-scholarship-loss", label: "BLOCKS_DISBURSAL", type: "CAUSED_BY", attributes: {}, confidence: 1.0 }
      ],
      stats: { total_nodes: 5, total_edges: 4, facts_count: 3, inferences_count: 0, rules_count: 1, contradictions_count: 0 }
    };
  },

  async resetMockState() {
    try {
      const res = await fetch(`${API_BASE}/reset`, { method: 'POST' });
      if (res.ok) return await res.json();
    } catch (e) {}
    localCaseStore = {
      "case-flagship-dbt-8821": { ...MOCK_FLAGSHIP_CASE },
      "case-epfo-claim-9912": { ...MOCK_EPFO_CASE },
      "case-pmay-housing-7734": { ...MOCK_PMAY_CASE }
    };
    return { status: "RESET" };
  }
};
