import React from 'react';
import { FileText, X, Copy, Check } from 'lucide-react';
import type { Case } from '../types';

interface IndraPetitionModalProps {
  currentCase: Case;
  onClose: () => void;
}

export const IndraPetitionModal: React.FC<IndraPetitionModalProps> = ({
  currentCase,
  onClose,
}) => {
  const [copied, setCopied] = React.useState(false);
  const action = currentCase.actions?.[0];

  const petitionText = action?.generated_content || `MEMORANDUM & STATUTORY REPRESENTATION
To: The Branch Manager, Canara Bank / State Bank of India
Subject: Immediate Remapping of Aadhaar APBS Mandate for Central DBT Entitlements

1. BENEFICIARY DETAILS:
   Citizen Name: ${currentCase.citizen_name}
   Aadhaar Token: ****-****-8821
   Entitlement Scheme: Ministry of Social Justice Post-Matric Scholarship (AY 2025-26)
   Entitlement Value: INR 48,000.00

2. FACTUAL GROUNDING:
   - On 2026-02-12, central PFMS payment batch failed with Error Code BNS-410.
   - Investigation confirms Canara Bank Account *4401 was placed under operational debit freeze.
   - Consequently, the central NPCI APBS mapper was designated INACTIVE.

3. LEGAL PRECEDENT & STATUTORY RELIEF:
   - As per Gujarat High Court (R/SCR.A/1908/2023), omnibus freezes on entire citizen accounts violate proportionality.
   - Under RBI Master Direction DPSS.CO.PD.No.1810, banks must honor customer mandate to remap APBS routing to active accounts.
   
4. RELIEF SOUGHT:
   - Immediate synchronization of NPCI mapper to State Bank of India Account No: *8812.
   - Restoration of ACTIVE APBS routing status for upcoming PFMS payment cycles.

Digitally generated by INDRA Autonomous Administrative Core.`;

  const handleCopy = () => {
    navigator.clipboard.writeText(petitionText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center p-4 sm:p-6 font-sans">
      <div className="bg-white border border-slate-200 rounded-3xl max-w-2xl w-full shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900">Prepared Legal Petition Dossier</h3>
              <p className="text-[11px] text-slate-400">
                Statutory Representation under RBI & High Court Mandate
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-xl text-slate-500 hover:text-slate-900 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto space-y-4 flex-1 bg-[#FAFAFA]">
          <div className="p-5 bg-white border border-slate-200 rounded-2xl shadow-xs font-mono text-xs text-slate-800 whitespace-pre-wrap leading-relaxed">
            {petitionText}
          </div>

          <div className="flex items-center justify-between pt-2">
            <button
              onClick={handleCopy}
              className="px-4 py-2.5 bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 rounded-xl text-xs font-bold flex items-center space-x-2 transition-all cursor-pointer"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied to Clipboard' : 'Copy Memorandum'}</span>
            </button>

            <button
              onClick={onClose}
              className="px-5 py-2.5 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold transition-all cursor-pointer"
            >
              Close Dossier
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
