import React from 'react';
import type { Case } from '../types';

interface IndraPetitionModalProps {
  currentCase: Case;
  onClose: () => void;
}

export const IndraPetitionModal: React.FC<IndraPetitionModalProps> = ({
  currentCase,
  onClose,
}) => {
  const [copied, setCopied] = React.useState(false);
  const action = currentCase.actions?.[0];

  const petitionText = action?.generated_content || `MEMORANDUM & STATUTORY REPRESENTATION
To: The Branch Manager, Canara Bank / State Bank of India
Subject: Immediate Remapping of Aadhaar APBS Mandate for Central DBT Entitlements

1. BENEFICIARY DETAILS:
   Citizen Name: ${currentCase.citizen_name}
   Aadhaar Token: ****-****-8821
   Entitlement Scheme: Ministry of Social Justice Post-Matric Scholarship (AY 2025-26)
   Entitlement Value: INR 48,000.00

2. FACTUAL GROUNDING:
   - On 2026-02-12, central PFMS payment batch failed with Error Code BNS-410.
   - Investigation confirms Canara Bank Account *4401 was placed under operational debit freeze.
   - Consequently, the central NPCI APBS mapper was designated INACTIVE.

3. LEGAL PRECEDENT & STATUTORY RELIEF:
   - As per Gujarat High Court (R/SCR.A/1908/2023), omnibus freezes on entire citizen accounts violate proportionality.
   - Under RBI Master Direction DPSS.CO.PD.No.1810, banks must honor customer mandate to remap APBS routing to active accounts.
   
4. RELIEF SOUGHT:
   - Immediate synchronization of NPCI mapper to State Bank of India Account No: *8812.
   - Restoration of ACTIVE APBS routing status for upcoming PFMS payment cycles.

Digitally generated by INDRA Autonomous Administrative Core.`;

  const handleCopy = () => {
    navigator.clipboard.writeText(petitionText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-white/95 backdrop-blur-md flex flex-col font-sans overflow-y-auto animate-in fade-in duration-300">
      
      {/* Huge Header */}
      <div className="w-full max-w-5xl mx-auto px-8 py-12 flex justify-between items-start">
        <div>
          <h2 className="text-4xl sm:text-6xl font-black tracking-tighter uppercase leading-[0.9]">
            Legal<br />Petition
          </h2>
          <div className="mt-4 text-xs font-bold uppercase tracking-widest opacity-50 flex items-center space-x-2">
            <span>Prepared Statutory Representation</span>
            <span>•</span>
            <span className="text-black">READY TO TRANSMIT</span>
          </div>
        </div>
        
        <button
          onClick={onClose}
          className="text-4xl hover:opacity-50 transition-opacity cursor-pointer font-light leading-none"
        >
          ×
        </button>
      </div>

      {/* Stark Document Frame */}
      <div className="w-full max-w-3xl mx-auto px-8 pb-24">
        <div className="border-t-2 border-black pt-12 space-y-8">
          
          <div className="p-8 border border-black font-mono text-sm uppercase tracking-widest whitespace-pre-wrap leading-loose">
            {petitionText}
          </div>

          <div className="mt-16 pt-8 border-t border-black/10 flex justify-between items-center">
            <button
              onClick={handleCopy}
              className="text-xs font-bold uppercase tracking-widest hover:opacity-50 transition-opacity cursor-pointer flex items-center space-x-2"
            >
              <span>{copied ? '✓ COPIED TO CLIPBOARD' : 'COPY MEMORANDUM'}</span>
            </button>
            <button
              onClick={onClose}
              className="px-6 py-3 bg-black text-white text-xs font-bold uppercase tracking-widest hover:bg-black/80 transition-colors cursor-pointer"
            >
              Close Dossier
            </button>
          </div>

        </div>
      </div>

    </div>
  );
};
